/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#4a655a",
        "primary-dim": "#3e594e",
        "primary-container": "#cbe9db",
        "on-primary": "#e5fff2",
        "on-primary-container": "#3d574d",
        "secondary": "#4c626c",
        "secondary-dim": "#405660",
        "secondary-container": "#cee6f2",
        "on-secondary": "#f2faff",
        "on-secondary-container": "#3f555f",
        "tertiary": "#6c5c4d",
        "tertiary-dim": "#5f5142",
        "tertiary-container": "#fde7d3",
        "on-tertiary": "#fff7f3",
        "surface": "#fbf9f4",
        "surface-dim": "#dadad2",
        "surface-bright": "#fbf9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f4ed",
        "surface-container": "#efeee7",
        "surface-container-high": "#e9e8e1",
        "surface-container-highest": "#e3e3db",
        "on-surface": "#31332e",
        "on-surface-variant": "#5e6059",
        "outline": "#7a7b75",
        "outline-variant": "#b2b2ab",
        "error": "#a83836",
        "error-container": "#fa746f",
        "on-error": "#fff7f6",
        "on-error-container": "#6e0a12",
        "background": "#fbf9f4",
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
    },
  },
  plugins: [],
}
